package test_project;

@license(LGPL);
//
// TODO documentation
//
//network Network
//{
//    parameters:
//        int WS;
//        int TO;
//        double PT;
//        double TD;
//        double ED;
//        double DD;
//        double LP;
//    submodules:
//        coordinator: Coordinator {
//            @display("p=174,175");
//        }
//        node0: Node {
//            @display("p=275,92");
//        }
//        node1: Node {
//            @display("p=65,92");
//        }
//    connections:
//        node0.out --> node1.in_node;
//        node1.out --> node0.in_node;
//        coordinator.out_node0 --> node0.in_coordinator;
//        coordinator.out_node1 --> node1.in_coordinator;
//}

